apply from: '../../constants.gradle'
apply plugin: 'com.android.library'

android {
    namespace project.ext.nlp_applicationId + ".artifacts"

    compileSdk project.ext.compileSdk
    buildToolsVersion project.ext.buildToolsVersion

    compileOptions {
        sourceCompatibility project.ext.javaVersion
        targetCompatibility project.ext.javaVersion
    }

    defaultConfig {
        targetSdk project.ext.targetSdk
        minSdk    Math.min(project.ext.app_aosp_minSdk, project.ext.nlp_minSdk)
    }

    buildFeatures {
        aidl        = true
        buildConfig = false
    }

    buildTypes {
        release {
            debuggable      false
            jniDebuggable   false
            minifyEnabled   true
            proguardFiles = [
                "proguard-rules.txt",
                getDefaultProguardFile('proguard-android.txt')
            ]
        }
        debug {
            debuggable      true
            jniDebuggable   true
            minifyEnabled   false
        }
    }

    lintOptions {
        disable 'MissingTranslation'
        abortOnError true
    }
}

dependencies {
}
