apply from: '../constants.gradle'
apply plugin: 'com.android.application'

android {
    namespace project.ext.app_applicationId

    compileSdkVersion project.ext.compileSdkVersion
    buildToolsVersion project.ext.buildToolsVersion

    compileOptions {
        sourceCompatibility project.ext.javaVersion
        targetCompatibility project.ext.javaVersion
    }

    defaultConfig {
        applicationId    project.ext.app_applicationId
        targetSdkVersion project.ext.targetSdkVersion

        applicationVariants.all { variant ->
            variant.outputs.all { output ->
                def variantName = variant.name.toLowerCase()

                if (variantName.contains("withaosplocationproviders")) {
                    if (variantName.contains("withbackuprestoresaf")) {
                        output.versionCodeOverride = project.ext.app_aosp_withSAF_releaseVersionCode
                        output.versionNameOverride = project.ext.app_aosp_withSAF_releaseVersion
                    }
                    else if (variantName.contains("withbackuprestorefilechooser")) {
                        output.versionCodeOverride = project.ext.app_aosp_withFileChooser_releaseVersionCode
                        output.versionNameOverride = project.ext.app_aosp_withFileChooser_releaseVersion
                    }
                    else {
                        output.versionCodeOverride = project.ext.app_aosp_releaseVersionCode
                        output.versionNameOverride = project.ext.app_aosp_releaseVersion
                    }
                }

                outputFileName = "${archivesBaseName}-${variant.versionName}-${variant.productFlavors[0].name}-${variant.productFlavors[1].name}-${variant.productFlavors[2].name}-${variant.buildType.name}.apk"
            }
        }
    }

    flavorDimensions "languageResources", "locationProvider", "fileImport"

    productFlavors {
        withAllLanguageTranslations {
            dimension "languageResources"
        }
        english {
            dimension "languageResources"
        }
        withAospLocationProviders {
            dimension "locationProvider"
        }
        withGooglePlayServicesFusedLocationProvider {
            dimension "locationProvider"

            minSdkVersion project.ext.app_gms_minSdkVersion
            versionCode   project.ext.app_gms_releaseVersionCode
            versionName   project.ext.app_gms_releaseVersion

            repositories {
                maven { url 'https://maven.google.com' }
            }
        }
        withHuaweiMobileServicesFusedLocationProvider {
            dimension "locationProvider"

            minSdkVersion project.ext.app_hms_minSdkVersion
            versionCode   project.ext.app_hms_releaseVersionCode
            versionName   project.ext.app_hms_releaseVersion

            repositories {
                maven { url 'https://developer.huawei.com/repo/' }
            }
        }
        noBackupRestore {
            dimension "fileImport"

            buildConfigField "boolean", "ENABLE_BACKUP_RESTORE", "false"
        }
        withBackupRestoreFileChooser {
            dimension "fileImport"

            buildConfigField "boolean", "ENABLE_BACKUP_RESTORE", "true"
        }
        withBackupRestoreSAF {
            dimension "fileImport"

            buildConfigField "boolean", "ENABLE_BACKUP_RESTORE", "true"
        }
    }

    buildFeatures {
        aidl        = false
        buildConfig = true
    }

    buildTypes {
        release {
            debuggable      false
            jniDebuggable   false
            minifyEnabled   true
            shrinkResources true
            proguardFiles = [
                "proguard-rules.txt",
                getDefaultProguardFile('proguard-android.txt')
            ]
        }
        debug {
            debuggable      true
            jniDebuggable   true
            minifyEnabled   false
            shrinkResources false
        }
    }

    dependenciesInfo {
        includeInApk    = false  // Disables dependency metadata when building APKs.
        includeInBundle = false  // Disables dependency metadata when building Android App Bundles.
    }

    lintOptions {
        disable 'MissingTranslation'
        abortOnError true
    }
}

androidComponents {
    beforeVariants(selector().all()) { variant ->
        def variantName = variant.name.toLowerCase()

        if (variantName.contains("withaosplocationproviders")) {
            if (variantName.contains("withbackuprestoresaf")) {
                variant.minSdk = project.ext.app_aosp_withSAF_minSdkVersion
            }
            else if (variantName.contains("withbackuprestorefilechooser")) {
                variant.minSdk = project.ext.app_aosp_withFileChooser_minSdkVersion
            }
            else {
                variant.minSdk = project.ext.app_aosp_minSdkVersion
            }
        }
        else {
            if (variantName.contains("withbackuprestorefilechooser")) {
                variant.enable = false
            }
        }

        if (variant.buildType == "release") {
            if (variantName.contains("english")) {
                variant.enable = false
            }
        }
        else if (variant.buildType == "debug") {
            if (variantName.contains("withalllanguagetranslations")) {
                variant.enable = false
            }
        }
    }
}

dependencies {
    implementation project(':Mock-my-GPS-UnifiedNlp-Backend-artifacts')

    implementation 'com.google.code.gson:gson:'    + '2.8.6'                                                                    // (235 KB) https://mvnrepository.com/artifact/com.google.code.gson/gson

    withGooglePlayServicesFusedLocationProviderImplementation 'com.google.android.gms:play-services-base:'        + '18.2.0'    // (567 KB) https://mvnrepository.com/artifact/com.google.android.gms/play-services-base?repo=google
    withGooglePlayServicesFusedLocationProviderImplementation 'com.google.android.gms:play-services-location:'    + '21.0.1'    // (232 KB) https://mvnrepository.com/artifact/com.google.android.gms/play-services-location?repo=google

    withHuaweiMobileServicesFusedLocationProviderImplementation 'com.huawei.hms:base:'        + '6.0.1.302'                     // (248 KB) https://mvnrepository.com/artifact/com.huawei.hms/base
    withHuaweiMobileServicesFusedLocationProviderImplementation 'com.huawei.hms:location:'    + '6.0.0.302'                     // ( 93 KB) https://mvnrepository.com/artifact/com.huawei.hms/location

    withBackupRestoreFileChooserImplementation project(':file-and-folder-chooser')                                              //          https://github.com/warren-bank/Android-libraries/tree/fork/kashifo/android-folder-picker-library/material-design
}
