apply from: '../../constants.gradle'
apply plugin: 'com.android.library'

android {
  namespace "lib.folderpicker"

  compileSdk project.ext.compileSdk
  buildToolsVersion project.ext.buildToolsVersion

  compileOptions {
    sourceCompatibility project.ext.javaVersion
    targetCompatibility project.ext.javaVersion
  }

  defaultConfig {
    minSdk    9
    targetSdk project.ext.targetSdk
  }

  lintOptions {
    disable 'MissingTranslation'
    abortOnError true
  }
}

dependencies {
}
