apply from: '../../constants.gradle'
apply plugin: 'com.android.library'

android {
  namespace "lib.folderpicker"

  compileSdkVersion project.ext.compileSdkVersion
  buildToolsVersion project.ext.buildToolsVersion

  compileOptions {
    sourceCompatibility project.ext.javaVersion
    targetCompatibility project.ext.javaVersion
  }

  defaultConfig {
    minSdkVersion    9
    targetSdkVersion project.ext.targetSdkVersion
  }

  lintOptions {
    disable 'MissingTranslation'
    abortOnError true
  }
}

dependencies {
}
