apply from: '../constants.gradle'
apply plugin: 'com.android.application'

android {
    namespace project.ext.shh_applicationId

    compileSdk project.ext.compileSdk
    buildToolsVersion project.ext.buildToolsVersion

    compileOptions {
        sourceCompatibility project.ext.javaVersion
        targetCompatibility project.ext.javaVersion
    }

    defaultConfig {
        minSdk    project.ext.shh_minSdk
        targetSdk project.ext.targetSdk

        applicationId project.ext.shh_applicationId
        versionCode   project.ext.shh_versionCode
        versionName   project.ext.shh_versionName

        archivesBaseName += "-$versionName"
    }

    flavorDimensions "languageResources"

    productFlavors {
        withAllLanguageTranslations {
            dimension "languageResources"
        }
        english {
            dimension "languageResources"
        }
    }

    buildFeatures {
        aidl        = false
        buildConfig = false
    }

    buildTypes {
        release {
            debuggable      false
            jniDebuggable   false
            minifyEnabled   true
            shrinkResources true
            proguardFiles = [
                "proguard-rules.txt",
                getDefaultProguardFile('proguard-android.txt')
            ]
        }
        debug {
            debuggable      true
            jniDebuggable   true
            minifyEnabled   false
            shrinkResources false
        }
    }

    dependenciesInfo {
        includeInApk    = false  // Disables dependency metadata when building APKs.
        includeInBundle = false  // Disables dependency metadata when building Android App Bundles.
    }

    lintOptions {
        disable 'MissingTranslation'
        abortOnError true
    }
}

dependencies {
}
